- WebContent/app/fix/header.jsp
- WebContent/assets/css/admin/adminMain.css
- WebContent/assets/css/fix/header.css
- WebContent/assets/css/fix/join.css
- WebContent/assets/js/fix/header.js
- src/com/seoulcheckin/app/member/CheckIdController.java
- src/com/seoulcheckin/app/member/MemberFrontController.java
- src/com/seoulcheckin/app/navigator/NavigatorFrontController.java
- src/com/seoulcheckin/app/navigator/dao/NavigatorDAO.java
- src/com/seoulcheckin/app/navigator/vo/NavigatorVO.java
- src/com/seoulcheckin/app/visa/vo/VisaVO.java
- src/com/seoulcheckin/mybatis/config/config.xml
- src/com/seoulcheckin/mybatis/mapper/MemberMapper.xml
Navigator와 Visa DB 테이블 분리로 인한 수정 및 header와 Member 파일 업데이트
> Navigator, Visa, header, Member 파일 업데이트

- src/com/seoulcheckin/mybatis/config/config.xml
> 컨피그 정리 및 bannerVO 추가

- src/com/seoulcheckin/mybatis/config/config.xml
> MemberVO 중복줄 제거

- src/com/seoulcheckin/app/visa/vo/VisaVO.java
- src/com/seoulcheckin/mybatis/config/config.xml
visaVO 수정 / config alias VISA 부분 추가하였습니다
> visaVO string->int 변경 / config alias 추가

- src/com/seoulcheckin/app/school/vo/SchoolDTO.java
> SchoolDTO 추가

- WebContent/app/fix/header.jsp
- WebContent/assets/css/fix/join.css
- WebContent/assets/js/fix/header.js
- src/com/seoulcheckin/app/member/JoinOkController.java
- src/com/seoulcheckin/app/member/LoginOkController.java
- src/com/seoulcheckin/app/member/MemberFrontController.java
- src/com/seoulcheckin/app/member/VerificationController.java
- src/com/seoulcheckin/app/member/dao/MemberDAO.java
- src/com/seoulcheckin/app/navigator/dao/NavigatorDAO.java
- src/com/seoulcheckin/mybatis/mapper/MemberMapper.xml
> 로그인 및 회원가입 서비스 관련 파일 업데이트

- WebContent/app/fix/header.jsp
- WebContent/assets/css/fix/join.css
- WebContent/assets/js/fix/header.js
- src/com/seoulcheckin/app/member/LoginOkController.java
- src/com/seoulcheckin/app/member/LogoutController.java
- src/com/seoulcheckin/app/member/MemberFrontController.java
- src/com/seoulcheckin/app/member/VerificationController.java
> 로그인 서비스 관련 파일 업데이트

- WebContent/app/member/myPageClass.jsp
- WebContent/app/member/myPageMain.jsp
- src/com/seoulcheckin/app/board/dao/EBoardDAO.java
- src/com/seoulcheckin/app/board/dao/KBoardDAO.java
- src/com/seoulcheckin/app/board/vo/EBoardVO.java
- src/com/seoulcheckin/app/board/vo/KBoardVO.java
- src/com/seoulcheckin/app/comment/dao/ECommentDAO.java
- src/com/seoulcheckin/app/comment/dao/KCommentDAO.java
- src/com/seoulcheckin/app/comment/vo/ECommentVO.java
- src/com/seoulcheckin/app/comment/vo/KCommentVO.java
- src/com/seoulcheckin/app/member/LoginOkController.java
- src/com/seoulcheckin/app/member/MemberFrontController.java
- src/com/seoulcheckin/mybatis/config/config.xml
- src/com/seoulcheckin/mybatis/mapper/BoardMapper.xml
- src/com/seoulcheckin/mybatis/mapper/EBoardMapper.xml
- src/com/seoulcheckin/mybatis/mapper/ECommentMapper.xml
- src/com/seoulcheckin/mybatis/mapper/KBoardMapper.xml
- src/com/seoulcheckin/mybatis/mapper/KCommentMapper.xml
- src/com/seoulcheckin/mybatis/mapper/MyProgramMapper.xml
Config.xml 파일 수정 및 VO 수정 업데이트합니다.
> Config.xml 파일 수정 및 VO 수정

- WebContent/app/visa/visanavigator.jsp
- src/com/seoulcheckin/app/navigator/dao/NavigatorDAO.java
- src/com/seoulcheckin/app/visa/VisaFrontController.java
- src/com/seoulcheckin/app/visa/VisaResultController.java
- src/com/seoulcheckin/app/visa/dao/VisaDAO.java
- src/com/seoulcheckin/mybatis/mapper/NavigatorMapper.xml
- src/com/seoulcheckin/mybatis/mapper/VisaMapper.xml
> VISA - dao/ FrontController/ Controller/ Mapper / Navigator

- WebContent/assets/css/main/test.css
- WebContent/assets/js/main/test.js
- src/com/seoulcheckin/app/banner/BannerFrontController.java
- src/com/seoulcheckin/app/banner/SelectController.java
- src/com/seoulcheckin/app/banner/dao/BannerDAO.java
- src/com/seoulcheckin/mybatis/mapper/BannerMapper.xml
최신 업로드사진 경로 ajax 로 메인에 select 해오기 입니다
> 최신 업로드사진경로 ajax 로 메인에 select 해오기

- WebContent/app/fix/header.jsp
- WebContent/assets/js/fix/header.js
- WebContent/assets/js/main/test.js
- src/com/seoulcheckin/app/banner/BannerFrontController.java
- src/com/seoulcheckin/app/banner/SelectController.java
- src/com/seoulcheckin/app/banner/dao/BannerDAO.java
- src/com/seoulcheckin/app/member/LoginOkController.java
- src/com/seoulcheckin/app/member/LogoutController.java
- src/com/seoulcheckin/app/member/MemberFrontController.java
> 로그인 서비스 수정 및 배너 관련 수정

- WebContent/app/member/myPageChange.jsp
- src/com/seoulcheckin/app/member/UpdateInfoController.java
- src/com/seoulcheckin/app/member/UpdateInfoOkController.java
- src/com/seoulcheckin/app/member/dao/MemberDAO.java
- src/com/seoulcheckin/mybatis/mapper/MemberMapper.xml
> 마이페이지 정보수정부분 업데이트 

- WebContent/app/visa/visanavigator.jsp
- src/com/seoulcheckin/app/navigator/NavigatorFrontController.java
- src/com/seoulcheckin/app/navigator/dao/NavigatorDAO.java
- src/com/seoulcheckin/app/visa/VisaFrontController.java
- src/com/seoulcheckin/app/visa/VisaResultController.java
- src/com/seoulcheckin/app/visa/dao/VisaDAO.java
- src/com/seoulcheckin/mybatis/mapper/NavigatorMapper.xml
- src/com/seoulcheckin/mybatis/mapper/VisaMapper.xml
navigator와 visa부분 frontController DAO Mapper수정
visaresultController 수정 visanavigator.jsp 완성 했습니다 
DB부분 추가예정입니다
> navigator와 visa부분 frontController DAO Mapper수정

- WebContent/app/fix/header.jsp
- WebContent/assets/js/fix/header.js
- src/com/seoulcheckin/app/member/LoginGoogleController.java
- src/com/seoulcheckin/app/member/MemberFrontController.java
- src/com/seoulcheckin/app/member/dao/MemberDAO.java
- src/com/seoulcheckin/mybatis/mapper/MemberMapper.xml
> 로그인 관련 업데이트

- WebContent/app/member/myPageChange.jsp
- WebContent/app/member/myPageClass.jsp
- WebContent/app/member/myPageCommunity.jsp
- WebContent/app/member/myPageDelete.jsp
- WebContent/app/member/myPageMain.jsp
- WebContent/app/member/myPageMessage.jsp
- WebContent/app/member/myPagePassword.jsp
- WebContent/app/member/mycomment.jsp
- WebContent/assets/js/fix/header.js
- src/com/seoulcheckin/app/member/MemberFrontController.java
- src/com/seoulcheckin/app/member/UpdateInfoController.java
- src/com/seoulcheckin/app/member/UpdateInfoOkController.java
- src/com/seoulcheckin/app/member/dao/MemberDAO.java
- src/com/seoulcheckin/mybatis/mapper/MemberMapper.xml
> 마이페이지 경로 잡고, 내정보 수정 업데이트 입니다 

- WebContent/assets/js/main/test.js
- src/com/seoulcheckin/app/member/LoginKakaoController.java
- src/com/seoulcheckin/app/member/LoginNaverController.java
- src/com/seoulcheckin/app/member/MemberFrontController.java
> 로그인 관련 파일 업데이트

- WebContent/app/fix/header.jsp
> header.jsp 파일 업데이트

- WebContent/WEB-INF/web.xml
- src/com/seoulcheckin/app/board/vo/EBoardDTO.java
- src/com/seoulcheckin/app/board/vo/KBoardDTO.java
- src/com/seoulcheckin/mybatis/config/config.xml
> web.xml, config.xml 수정과 추가

- WebContent/WEB-INF/web.xml
- WebContent/app/map/map.jsp
- WebContent/assets/css/map/seoulPage.css
- WebContent/assets/js/map/seoulPage.js
- src/com/seoulcheckin/app/map/MapDetailController.java
- src/com/seoulcheckin/app/map/MapFilterController.java
- src/com/seoulcheckin/app/map/MapFrontController.java
- src/com/seoulcheckin/app/map/dao/MapDAO.java
- src/com/seoulcheckin/mybatis/mapper/MapMapper.xml
> map 관련 변경 사항 추가 및 수정

- src/com/seoulcheckin/app/faq/vo/FaqVO.java
- src/com/seoulcheckin/app/navigator/vo/NavigatorVO.java
- src/com/seoulcheckin/app/notice/vo/NoticeVO.java
- src/com/seoulcheckin/app/visa/vo/VisaVO.java
NoticeVO FaqVO 수정.주석 완료 VisaVO NavigatorVO 주석완료했습니다
> NoticeVO FaqVO 수정.주석 완료 VisaVO NavigatorVO 주석완료

- src/com/seoulcheckin/app/comment/vo/ECommentDTO.java
- src/com/seoulcheckin/app/comment/vo/KCommentDTO.java
- src/com/seoulcheckin/mybatis/config/config.xml
config 추가하고  CommentDTO 추가했습니다.
> config 추가 및 DTO 추가

- WebContent/app/fix/header.jsp
- WebContent/app/member/myPageChange.jsp
- WebContent/app/member/myPageClass.jsp
- WebContent/app/member/myPageCommunity.jsp
- WebContent/app/member/myPageDelete.jsp
- WebContent/app/member/myPageMain.jsp
- WebContent/app/member/myPageMessage.jsp
- WebContent/app/member/myPagePassword.jsp
- WebContent/app/member/mycomment.jsp
- src/com/seoulcheckin/app/member/DropInfoOkController.java
- src/com/seoulcheckin/app/member/MemberFrontController.java
- src/com/seoulcheckin/app/member/MyMsgController.java
- src/com/seoulcheckin/app/member/MyPageController.java
- src/com/seoulcheckin/app/member/SelectBoardCountController.java
- src/com/seoulcheckin/app/member/SelectMessageCountController.java
- src/com/seoulcheckin/app/member/SelectProgramCountController.java
- src/com/seoulcheckin/app/member/dao/MemberDAO.java
- src/com/seoulcheckin/app/member/vo/MemberDTO.java
- src/com/seoulcheckin/mybatis/config/config.xml
- src/com/seoulcheckin/mybatis/mapper/MemberMapper.xml
회원탈퇴,  마이페이지 메인 ajax 추가, 맴버 DTO 추가, confing 설정
> 회원탈퇴,  마이페이지 메인 ajax 추가, 맴버 DTO 추가, confing 설정

- WebContent/app/faq/support_section2_loc.jsp
- WebContent/app/faq/support_section3_for.jsp
- WebContent/app/notice/support.jsp
- src/com/seoulcheckin/app/faq/dao/FaqDAO.java
- src/com/seoulcheckin/app/notice/ForDetailController.java
- src/com/seoulcheckin/app/notice/LocDetailController.java
- src/com/seoulcheckin/app/notice/NoticeDetailController.java
- src/com/seoulcheckin/app/notice/NoticeFrontController.java
- src/com/seoulcheckin/app/notice/NoticeListController.java
- src/com/seoulcheckin/app/notice/SearchResultController.java
- src/com/seoulcheckin/app/notice/dao/NoticeDAO.java
- src/com/seoulcheckin/mybatis/mapper/FaqMapper.xml
- src/com/seoulcheckin/mybatis/mapper/NoticeMapper.xml
FAQ, NOTICE _ 페이지 이동 완료 Controller, jsp 추가 했습니다
> FAQ, NOTICE _ 페이지 이동 완료 Controller, jsp 추가

- WebContent/app/member/myPageMessage.jsp
- WebContent/assets/css/member/myPageMessage.css
- WebContent/assets/js/main/test.js
- src/com/seoulcheckin/app/member/MemberFrontController.java
- src/com/seoulcheckin/app/member/MyMsgController.java
- src/com/seoulcheckin/app/member/MyPostController.java
- src/com/seoulcheckin/app/member/SelectBoardCountController.java
- src/com/seoulcheckin/app/member/SelectMessageCountController.java
- src/com/seoulcheckin/app/member/SelectProgramCountController.java
- src/com/seoulcheckin/app/member/dao/MemberDAO.java
- src/com/seoulcheckin/app/member/vo/MemberDTO.java
- src/com/seoulcheckin/app/message/dao/MessageDAO.java
- src/com/seoulcheckin/app/myprogram/dao/MyProgramDAO.java
- src/com/seoulcheckin/mybatis/mapper/KBoardMapper.xml
- src/com/seoulcheckin/mybatis/mapper/MemberMapper.xml
- src/com/seoulcheckin/mybatis/mapper/MessageMapper.xml
- src/com/seoulcheckin/mybatis/mapper/MyProgramMapper.xml
- src/com/seoulcheckin/mybatis/mapper/SchoolMapper.xml
마이페이지 쪽지함  목록, 페이징, 나의 게시글 컨트롤러 까지 입니다
> 마이페이지 쪽지함  목록, 페이징, 나의 게시글 컨트롤러 까지 입니다

- WebContent/app/fix/header.jsp
- WebContent/app/member/myPageChange.jsp
- WebContent/app/member/myPageClass.jsp
- WebContent/app/member/myPageCommunity.jsp
- WebContent/app/member/myPageDelete.jsp
- WebContent/app/member/myPageMain.jsp
- WebContent/app/member/myPageMessage.jsp
- WebContent/app/member/mycomment.jsp
- src/com/seoulcheckin/app/board/dao/KBoardDAO.java
- src/com/seoulcheckin/app/member/DropInfoController.java
- src/com/seoulcheckin/app/member/DropInfoOkController.java
- src/com/seoulcheckin/app/member/MemberFrontController.java
- src/com/seoulcheckin/app/member/MyClassController.java
- src/com/seoulcheckin/app/member/MyCommentController.java
- src/com/seoulcheckin/app/member/MyPageController.java
- src/com/seoulcheckin/app/member/MyPostController.java
- src/com/seoulcheckin/app/member/ProfileController.java
- src/com/seoulcheckin/app/member/UpdateInfoController.java
- src/com/seoulcheckin/app/member/UpdateInfoOkController.java
- src/com/seoulcheckin/app/member/dao/MemberDAO.java
- src/com/seoulcheckin/mybatis/mapper/KBoardMapper.xml
- src/com/seoulcheckin/mybatis/mapper/MemberMapper.xml
프론트컨트롤러 경로 정리, 파일 정리 , 마이페이지 ajax 추가 , 헤더 글자 , 위치 조정,
> 프론트컨트롤러 경로 정리, 파일 정리 , 마이페이지 ajax 추가 , 헤더 글자 , 위치 조정,

- WebContent/app/faq/support_searchResult.jsp
- WebContent/app/faq/support_section.jsp
- WebContent/app/faq/support_section2_loc.jsp
- WebContent/app/faq/support_section3_for.jsp
- WebContent/app/notice/support.jsp
- WebContent/assets/css/notice/support.css
- WebContent/assets/css/notice/support_section.css
- src/com/seoulcheckin/app/faq/dao/FaqDAO.java
- src/com/seoulcheckin/app/notice/NoticeDetailController.java
- src/com/seoulcheckin/app/notice/NoticeFrontController.java
- src/com/seoulcheckin/app/notice/SearchResultController.java
- src/com/seoulcheckin/app/notice/dao/NoticeDAO.java
- src/com/seoulcheckin/mybatis/mapper/FaqMapper.xml
- src/com/seoulcheckin/mybatis/mapper/NoticeMapper.xml
> 네비게이터, 공지사항 수정완료
